# Generated by Django 6.0.1 on 2026-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Lignum & Lux', max_length=255)),
                ('hero_subtitle', models.CharField(default='Timeless Elegance in Wood', max_length=255)),
                ('hero_image_url', models.CharField(blank=True, max_length=512)),
                ('hero_background_url', models.CharField(blank=True, max_length=512)),
                ('contact_email', models.EmailField(default='contact@lignumandlux.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 9876543210', max_length=20)),
                ('business_address', models.TextField(default='123, Wood Street, Bangalore')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
    ]
