# Generated by Django 6.0.1 on 2026-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_background_url',
            field=models.ImageField(blank=True, null=True, upload_to='site_config/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='site_config/'),
        ),
    ]
