# Generated by Django 6.0.1 on 2026-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_siteconfig_hero_background_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='b2b_partial_payment_percentage',
            field=models.IntegerField(default=50, help_text='Percentage of total amount to be paid upfront for B2B orders'),
        ),
    ]
