# Generated by Django 6.0.1 on 2026-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_siteconfig_b2b_partial_payment_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(default='contact@atozwoodart.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='A TO Z WoodArt', max_length=255),
        ),
    ]
