# Generated by Django 6.0.1 on 2026-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='default_from_email',
            field=models.CharField(default='noreply@atozwoodart.com', max_length=255),
        ),
    ]
