# Generated by Django 6.0.1 on 2026-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Decor', 'Decor'), ('Kitchen', 'Kitchen'), ('Lighting', 'Lighting'), ('Tools', 'Tools')], max_length=50)),
                ('image_url', models.URLField()),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
