# Generated by Django 6.0.1 on 2026-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_partner_logo_url_alter_partner_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b2b_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(default=1),
        ),
    ]
