# Generated by Django 6.0.1 on 2026-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse_address',
            field=models.TextField(blank=True),
        ),
    ]
