# Generated by Django 6.0.1 on 2026-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_business_address_user_gst_number_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
