# Generated by Django 6.0.1 on 2026-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
